Repository AaronSosaRamos/conversors-suite, pull requests merged in 2024-09, with the labels that each got.

#6 New upates 17 09 2024
  components/JsonFormatterForm.tsx
  components/MarkdownForm.tsx
  components/PDFButton.tsx
  yarn.lock
Labels: documentation, enhancement, help wanted, good first issue

#7 new json to sql imp.
  app/json-formatter/page.tsx
  app/json-to-sql/page.tsx
  components/JsonToSqlForm.tsx
  components/MainPage.tsx
  components/ReusableLayout.tsx
  package.json
  yarn.lock
Labels: documentation, enhancement, good first issue

#9 feature/math-to-latex imp.
  app/math-to-latex/page.tsx
  components/MathFormulaToLaTeXForm.tsx
  package.json
  yarn.lock
Labels: documentation, enhancement, help wanted, good first issue

#10 new feature/translation imp.
  app/translator/page.tsx
  components/TranslatorForm.tsx
  package.json
  yarn.lock
Labels: documentation, enhancement, help wanted, good first issue

#11 Feature/info to text
  app/info-to-table/page.tsx
  components/InfoToTableForm.tsx
  components/TranslatorForm.tsx
  package.json
  yarn.lock
Labels: documentation, enhancement, help wanted, good first issue

#12 new feature/image-transcription imp
  app/image-transcription/page.tsx
  components/ImageTranscriptionForm.tsx
Labels: documentation, enhancement, help wanted, good first issue

#13 Update ReusableLayout.tsx
  components/ReusableLayout.tsx
Labels: documentation, enhancement, help wanted, good first issue

#14 integration/json-to-sql
  .env.local.sample
  components/JsonToSqlForm.tsx
  package.json
  services/api.ts
  yarn.lock
Labels: documentation, enhancement, help wanted, good first issue

#15 integration/xml-to-sql
  components/XmlToSqlForm.tsx
Labels: documentation, enhancement, help wanted, good first issue

#16 integration/math-to-latex
  components/MathFormulaToLaTeXForm.tsx
Labels: documentation, enhancement, help wanted, good first issue

#17 integration/translator
  components/TranslatorForm.tsx
Labels: documentation, enhancement, help wanted, good first issue

#18 integration/info-to-table
  components/InfoToTableForm.tsx
Labels: documentation, enhancement, good first issue

#19 integration/image-transcription
  components/ImageTranscriptionForm.tsx
Labels: documentation, enhancement, good first issue

#20 new-main-screen-18-09-2024
  components/MainPage.tsx
Labels: enhancement, help wanted, good first issue
